routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::get('/locale/{locale}', function($locale){
    \Session::put('locale',$locale);
    return redirect()->back();
})->name('locale');
Route::resource('cashes', 'CashController');
Route::resource('debts', 'DebtController');
Route::resource('lands', 'LandController');
Route::resource('deposits', 'DepositController');
Route::resource('drawings', 'DrawingController');
Route::resource('commodities', 'CommodityController');
Route::resource('bonds', 'BondController');
Route::resource('repos', 'RepoController');
Route::resource('stocks', 'StockController');
Route::resource('cryptocurrencies', 'CryptocurrencyController');
Route::resource('houses', 'HouseController');
Route::resource('cars', 'CarController');
Route::resource('animals', 'AnimalController');
Route::resource('others', 'OtherController');
Route::get('/wealth','WealthController@index')->name('wealth');

resources/views/index_pages/bond.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.bonds')</div>
                        @if($bonds->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.name_of_bank')</th>
                                                <th>@lang('portfolio.currency')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.interest_rate')</th>
                                                <th>@lang('portfolio.withholding_rate')</th>
                                                <th>@lang('portfolio.date_start')</th>
                                                <th>@lang('portfolio.date_end')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($bonds as $bond)
                                            <tr>
                                                <td>{{$bond->name_of_bank}}</td>
                                                <td>{{$bond->currency}}</td>
                                                <td>{{number_format($bond->amount,2,'.','')}}</td>  
                                                <td>{{$bond->interest_rate}}</td>
                                                <td>{{$bond->withholding_rate}}</td>
                                                <td>{{date("d.m.Y", strtotime($bond->start))}}</td>
                                                <td>{{date("d.m.Y", strtotime($bond->end))}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("bonds.edit",['id'=>$bond->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['BondController@destroy', 'id'=>$bond->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $bonds->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/car.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.cars')</div>
                        @if($cars->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.model')</th>
                                                <th>@lang('portfolio.price')</th>
                                                <th>@lang('portfolio.possesion_date')</th>
                                                <th>@lang('portfolio.commission_rate')</th>
                                                <th>@lang('portfolio.sold')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($cars as $car)
                                            <tr>
                                                <td>{{$car->model}}</td>
                                                <td>{{$car->price}}</td> 
                                                <td>{{date("d.m.Y", strtotime($car->possesion_date))}}</td>
                                                <td>{{$car->commission_rate}}</td>
                                                <td>{{$car->sold ? __('portfolio.sold') : __('portfolio.not_sold')}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("cars.edit",['id'=>$car->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['CarController@destroy', 'id'=>$car->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $cars->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/cash.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.cashes')</div>
                        @if($cashes->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.currency')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.possesion_date')</th>
                                                <th>@lang('portfolio.spent')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($cashes as $cash)
                                            <tr>
                                                <td>{{$cash->currency}}</td>
                                                <td>{{number_format($cash->amount,2,'.','')}}</td>  
                                                <td>{{date("d.m.Y", strtotime($cash->possesion_date))}}</td>
                                                <td>{{$cash->spent ? __('portfolio.yes') : __('portfolio.no')}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("cashes.edit",['id'=>$cash->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['CashController@destroy', 'id'=>$cash->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $cashes->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/commodity.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.commodity')</div>
                        @if($commodities->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.type')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.price')</th>
                                                <th>@lang('portfolio.commission_rate')</th>
                                                <th>@lang('portfolio.possesion_date')</th>
                                                <th>@lang('portfolio.sold')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($commodities as $commodity)
                                            <tr>
                                                <td>{{$commodity->type}}</td>
                                                <td>{{number_format($commodity->amount,2,'.','')}}</td>  
                                                <td>{{number_format($commodity->price,2,'.','')}}</td> 
                                                <td>{{$commodity->commission_rate}}</td>
                                                <td>{{date("d.m.Y", strtotime($commodity->possesion_date))}}</td>
                                                <td>{{$commodity->sold ? __('portfolio.yes') : __('portfolio.no')}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("commodities.edit",['id'=>$commodity->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['CommodityController@destroy', 'id'=>$commodity->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $commodities->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/cryptocurrency.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.cryptocurrencies')</div>
                        @if($cryptocurrencies->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.currency')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.possesion_date')</th>
                                                <th>@lang('portfolio.spent')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($cryptocurrencies as $cryptocurrency)
                                            <tr>
                                                <td>{{$cryptocurrency->currency}}</td>
                                                <td>{{number_format($cryptocurrency->amount,2,'.','')}}</td>  
                                                <td>{{date("d.m.Y", strtotime($cryptocurrency->possesion_date))}}</td>
                                                <td>{{$cash->spent ? __('portfolio.yes') : __('portfolio.no')}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("cryptocurrencies.edit",['id'=>$cryptocurrency->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['CryptocurrencyController@destroy', 'id'=>$cryptocurrency->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $cryptocurrencies->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/debt.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.debts')</div>
                        @if($debts->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.who')</th>
                                                <th>@lang('portfolio.currency')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.possesion_date')</th>
                                                <th>@lang('portfolio.paid')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($debts as $debt)
                                            <tr>
                                                <td>{{$debt->who}}</td>
                                                <td>{{$debt->currency}}</td>
                                                <td>{{number_format($debt->amount,2,'.','')}}</td>  
                                                <td>{{date("d.m.Y", strtotime($debt->possesion_date))}}</td>
                                                <td>{{$debt->paid ? __('portfolio.yes') : __('portfolio.no')}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("debts.edit",['id'=>$debt->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['DebtController@destroy', 'id'=>$debt->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $debts->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/deposit.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.deposit_accounts')</div>
                        @if($deposits->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.name_of_bank')</th>
                                                <th>@lang('portfolio.currency')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.interest_rate')</th>
                                                <th>@lang('portfolio.withholding_rate')</th>
                                                <th>@lang('portfolio.date_start')</th>
                                                <th>@lang('portfolio.date_end')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($deposits as $deposit)
                                            <tr>
                                                <td>{{$deposit->name_of_bank}}</td>
                                                <td>{{$deposit->currency}}</td>
                                                <td>{{number_format($deposit->amount,2,'.','')}}</td>  
                                                <td>{{$deposit->interest_rate}}</td>
                                                <td>{{$deposit->withholding_rate}}</td>
                                                <td>{{date("d.m.Y", strtotime($deposit->start))}}</td>
                                                <td>{{date("d.m.Y", strtotime($deposit->end))}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("deposits.edit",['id'=>$deposit->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['DepositController@destroy', 'id'=>$deposit->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $deposits->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/drawing.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-10 col-md-offset-1">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@lang('portfolio.drawing_accounts')</div>
                        @if($drawings->count() >0)
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>@lang('portfolio.name_of_bank')</th>
                                                <th>@lang('portfolio.currency')</th>
                                                <th>@lang('portfolio.amount')</th>
                                                <th>@lang('portfolio.date_start')</th>
                                                <th>@lang('portfolio.using')</th>
                                                <th>@lang('portfolio.edit')</th>
                                                <th>@lang('portfolio.delete')</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($drawings as $drawing)
                                            <tr>
                                                <td>{{$drawing->name_of_bank}}</td>
                                                <td>{{$drawing->currency}}</td>
                                                <td>{{number_format($drawing->amount,2,'.','')}}</td>  
                                                <td>{{date("d.m.Y", strtotime($drawing->start))}}</td>
                                                <td>{{$drawing->using ? __('portfolio.yes') : __('portfolio.no')}}</td>
                                                <td>
                                                    <a class="btn btn-primary" href="{{route("drawings.edit",['id'=>$drawing->id]) }}" role="button">@lang('portfolio.edit')</a></div>
                                                </td>
                                                <td>
                                                    {{ Form::open(['action' => ['DrawingController@destroy', 'id'=>$drawing->id], 'method' => 'delete','onsubmit' => 'return ConfirmDelete()']) }}
                                                        {{ Form::submit(__('portfolio.delete'), ['class'=>'btn btn-danger btn-mini']) }}
                                                    {{ Form::close() }}
                                                </td>
                                            </tr>
                                            @endforeach 
                                        </tbody>
                                    </table>
                                </div>
                                <div class="col-md-10 col-md-offset-2">{{ $drawings->links() }}</div>
                            </div>
                        @else
                            <p align="center" style="color:red">@lang('message.no_data')</p> 
                        @endif
                    </div>   
                </div>
        </div>  
    </div>
@endsection

resources/views/index_pages/wealth.blade.php
@extends('layouts.app')
@section('content')
    <div class='container'>
        <div class='row'>
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">@lang('portfolio.wealth_change_graph_in_dollar')</div>
                        <div class="card-body" id="wealthNet">
                            @if($userHasNoAsset == true)
                            <p style="color:red">@lang('message.no_data')</p>
                            @else
                            {!! $lavaWealth->render('LineChart','Wealth','wealthNet') !!}
                            @endif()
                        </div>
                    </div>   
                </div>
        </div>  
    </div>
@endsection